version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_service
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./tmp:/tmp

  # app:
  #   build: .
  #   container_name: node_service
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - MONGO_URI=mongodb://mongo:27017/services
  #   depends_on:
  #     - mongo

volumes:
  mongo-data:
